[files]
extend-exclude=[
  "experiments/*", 
  "support/*",
  "test/*",
  "*.lvt",
  "*.pvt",
  "*.tlg",
  "*.tpf",
  "*.eps"  
]

[default.extend-words]
WOMENS = "WOMENS"
Alph = "Alph"
OT = "OT"
10ths = "10ths"
BA = "BA"
EDE = "EDE"
ths ="ths"

[default.extend-identifiers]
atend = "atend"
thm   = "thm"
Fo    ="Fo"
portugues = "portugues"
Alph = "Alph"
alph = "alph"
OT = "OT"
ist = "ist"
multline = "multline"
Tabel = "Tabel"
abl = "abl"
agina = "agina"
inh = "inh"
Teorem = "Teorem"
BA = "BA"
rturned = "rturned"
ot ="ot"
EDE = "EDE"
TEH = "TEH"
