-- Build script for hyperref

-- Build script for hyperref
module = "hyperref"

docfiledir="doc"
docfiles={"doc/*.html"}
textfiles= {"*.md", "*.txt","*.html"}
installfiles = {'*.def','*.sty'}

checkconfigs = {"build","config-pvt","config-3","config-xetex"}
checkengines = {"pdftex","etex","luatex"}

-- temp settings disable checks while testing ctan build
-- testfiledir= "disabled" 
-- checkconfigs={}
-- checkengines = {"pdftex"}

checkruns = 2

-- start at getting ctan build organised, not complete yet (mkctan script still used)
sourcefiles        = {"*.dtx", "*.ins", "bmhydoc.sty","*-hyper.sty","paperslides99.zip","psdmapshortnames.pl","doc/*.???"}
typesetfiles={"doc/manual.tex","backref.dtx","hyperref.dtx","nameref.dtx"}


function docinit_hook ()
 return  runcmd("htlatex manual","doc",{"TEXINPUTS","LUAINPUTS"})
end

flatten = false
packtdszip  = true





-- ctanlocations and tdslocations
-- recording the layouts of the zip files
-- generated by the existing mkctan script
-- tdslocations is an l3build variable, ctanloacations
-- currently just for documentation

ctanlocations={
"hyperref.tds.zip",
"hyperref/ChangeLog.txt",
"hyperref/README.md",
"hyperref/backref.dtx",
"hyperref/backref.pdf",
"hyperref/bmhydoc.sty",
"hyperref/doc/cmmi10-22.gif",
"hyperref/doc/cmsy10-21.gif",
"hyperref/doc/manual.css",
"hyperref/doc/manual.html",
"hyperref/doc/manual.pdf",
"hyperref/doc/manual2.html",
"hyperref/doc/manual3.html",
"hyperref/doc/manual4.html",
"hyperref/doc/manual5.html",
"hyperref/doc/manual6.html",
"hyperref/doc/paper.pdf",
"hyperref/doc/slides.pdf",
"hyperref/hluatex.dtx",
"hyperref/hylatex.ltx",
"hyperref/hyperref.dtx",
"hyperref/hyperref.ins",
"hyperref/hyperref.pdf",
"hyperref/manifest.txt",
"hyperref/minitoc-hyper.sty",
"hyperref/nameref.dtx",
"hyperref/nameref.pdf",
"hyperref/ntheorem-hyper.sty",
"hyperref/paperslides99.zip",
"hyperref/psdmapshortnames.pl",
"hyperref/xr-hyper.sty"
}



tdslocations={
"doc/latex/hyperref/ChangeLog.txt",
"doc/latex/hyperref/README.md",
"doc/latex/hyperref/backref.pdf",
"doc/latex/hyperref/cmmi10-22.gif",
"doc/latex/hyperref/cmsy10-21.gif",
"doc/latex/hyperref/hyperref.pdf",
"doc/latex/hyperref/manifest.txt",
"doc/latex/hyperref/manual.css",
"doc/latex/hyperref/manual.html",
"doc/latex/hyperref/manual.pdf",
"doc/latex/hyperref/manual2.html",
"doc/latex/hyperref/manual3.html",
"doc/latex/hyperref/manual4.html",
"doc/latex/hyperref/manual5.html",
"doc/latex/hyperref/manual6.html",
"doc/latex/hyperref/nameref.pdf",
"doc/latex/hyperref/paper.pdf",
"doc/latex/hyperref/slides.pdf",
"source/latex/hyperref/backref.dtx",
"source/latex/hyperref/bmhydoc.sty",
"source/latex/hyperref/doc/fdl.tex",
"source/latex/hyperref/doc/manual.tex",
"source/latex/hyperref/doc/paperslides99.zip",
"source/latex/hyperref/hluatex.dtx",
"source/latex/hyperref/hyperref.dtx",
"source/latex/hyperref/hyperref.ins",
"source/latex/hyperref/nameref.dtx",
"source/latex/hyperref/psdmapshortnames.pl",
"tex/latex/hyperref/backref.sty",
"tex/latex/hyperref/hdvipdfm.def",
"tex/latex/hyperref/hdvips.def",
"tex/latex/hyperref/hdvipson.def",
"tex/latex/hyperref/hdviwind.def",
"tex/latex/hyperref/hluatex.def",
"tex/latex/hyperref/hpdftex.def",
"tex/latex/hyperref/htex4ht.cfg",
"tex/latex/hyperref/htex4ht.def",
"tex/latex/hyperref/htexture.def",
"tex/latex/hyperref/hvtex.def",
"tex/latex/hyperref/hvtexhtm.def",
"tex/latex/hyperref/hvtexmrk.def",
"tex/latex/hyperref/hxetex.def",
"tex/latex/hyperref/hylatex.ltx",
"tex/latex/hyperref/hyperref.sty",
"tex/latex/hyperref/hypertex.def",
"tex/latex/hyperref/minitoc-hyper.sty",
"tex/latex/hyperref/nameref.sty",
"tex/latex/hyperref/nohyperref.sty",
"tex/latex/hyperref/ntheorem-hyper.sty",
"tex/latex/hyperref/pd1enc.def",
"tex/latex/hyperref/pdfmark.def",
"tex/latex/hyperref/psdextra.def",
"tex/latex/hyperref/puarenc.def",
"tex/latex/hyperref/puenc.def",
"tex/latex/hyperref/puvnenc.def",
"tex/latex/hyperref/xr-hyper.sty"
}




kpse.set_program_name ("kpsewhich")
if not release_date then
 dofile ( kpse.lookup ("l3build.lua"))
end
