#!/bin/bash

# build hyperref ctan distrib
# perhaps use l3build one day, but not today



tex hyperref.ins
lualatex hyperref.dtx
lualatex hyperref.dtx

rm -rf hyperref-tds
mkdir hyperref-tds


mkdir hyperref-tds/doc
mkdir hyperref-tds/doc/latex
mkdir hyperref-tds/doc/latex/hyperref
cp ChangeLog ChangeLog.pdf README README.pdf hyperref.pdf  nameref.pdf doc/*.gif doc/manual{.css,.html,.pdf,2.html,3.html} doc/options.pdf doc/paper.pdf doc/slides.pdf \
  hyperref-tds/doc/latex/hyperref

mkdir hyperref-tds/source
mkdir hyperref-tds/source/latex
mkdir hyperref-tds/source/latex/hyperref
mkdir hyperref-tds/source/latex/hyperref/doc
cp doc/fdl.tex doc/manual.tex doc/options.tex \
  hyperref-tds/source/latex/hyperref/doc

cp -r test \
  hyperref-tds/source/latex/hyperref

cp backref.dtx bmhydoc.sty hyperref.dtx hyperref.ins nameref.dtx psdmapshortnames.pl \
  hyperref-tds/source/latex/hyperref

mkdir hyperref-tds/tex
mkdir hyperref-tds/tex/latex
mkdir hyperref-tds/tex/latex/hyperref

cp  backref.sty hdvipdfm.def hdvips.def hdvipson.def hdviwind.def hpdftex.def htex4ht.cfg htex4ht.def htexture.def hvtex.def hvtexhtm.def hvtexmrk.def hxetex.def hylatex.ltx hyperref.sty hypertex.def minitoc-hyper.sty nameref.sty nohyperref.sty ntheorem-hyper.sty pd1enc.def pdfmark.def psdextra.def puarenc.def puenc.def puvnenc.def xr-hyper.sty \
  hyperref-tds/tex/latex/hyperref

cd hyperref-tds
zip -r hyperref.tds.zip  doc source tex
mv hyperref.tds.zip ..



cd ../..
rm -f hyperref.zip
zip -r hyperref.zip hyperref/{hyperref.tds.zip,backref.dtx,backref.pdf,bmhydoc.sty,ChangeLog,ChangeLog.pdf,doc,hylatex.ltx,hyperref.dtx,hyperref.ins,hyperref.pdf,manifest.txt,minitoc-hyper.sty,nameref.dtx,nameref.pdf,ntheorem-hyper.sty,psdmapshortnames.pl,README,README.md,README.pdf,test,xr-hyper.sty}
