#!/bin/bash

# build hyperref ctan distrib
# perhaps use l3build one day, but not today



# unpack sources
tex hyperref.ins

# documented code
lualatex hyperref.dtx
makeindex -s gind.ist hyperref.idx
lualatex hyperref.dtx

lualatex nameref.dtx
makeindex -s gind.ist nameref.dtx
lualatex nameref.dtx

lualatex backref.dtx
makeindex -s gind.ist backref.dtx
lualatex backref.dtx


# clean directory to build TDS tree
rm -rf hyperref-tds
mkdir hyperref-tds

# xslt, you can also probably use xsltproc
saxon9  -versionmsg:off README.xml README_txt.xsl > README
saxon9  -versionmsg:off README.xml README_tex.xsl > README.tex
lualatex README.tex
lualatex README.tex

# xslt, you can also probably use xsltproc
saxon9  -versionmsg:off ChangeLog.xml ChangeLog_txt.xsl > ChangeLog
saxon9  -versionmsg:off ChangeLog.xml ChangeLog_tex.xsl > ChangeLog.tex
lualatex ChangeLog.tex
lualatex ChangeLog.tex

# move current package to doc directory
cp *.sty *.def doc
cd doc
# process manual as pdf and html
lualatex manual
lualatex manual

htlatex manual

lualatex options
lualatex options


# Build TDS tree
cd ..

mkdir hyperref-tds/doc
mkdir hyperref-tds/doc/latex
mkdir hyperref-tds/doc/latex/hyperref
cp ChangeLog ChangeLog.pdf README README.pdf hyperref.pdf  nameref.pdf backref.pdf doc/*.gif doc/manual{.css,.html,.pdf,2.html,3.html} doc/options.pdf doc/paper.pdf doc/slides.pdf \
  hyperref-tds/doc/latex/hyperref

mkdir hyperref-tds/source
mkdir hyperref-tds/source/latex
mkdir hyperref-tds/source/latex/hyperref
mkdir hyperref-tds/source/latex/hyperref/doc
cp doc/fdl.tex doc/manual.tex doc/options.tex \
   hyperref-tds/source/latex/hyperref/doc
cp paperslides99.zip hyperref-tds/source/latex/hyperref/doc

cp backref.dtx bmhydoc.sty hyperref.dtx hyperref.ins nameref.dtx hluatex.dtx psdmapshortnames.pl \
  hyperref-tds/source/latex/hyperref

mkdir hyperref-tds/tex
mkdir hyperref-tds/tex/latex
mkdir hyperref-tds/tex/latex/hyperref

cp  backref.sty hdvipdfm.def hdvips.def hdvipson.def hdviwind.def hpdftex.def htex4ht.cfg htex4ht.def htexture.def hvtex.def hvtexhtm.def hvtexmrk.def hxetex.def hylatex.ltx hyperref.sty hypertex.def minitoc-hyper.sty nameref.sty nohyperref.sty ntheorem-hyper.sty pd1enc.def pdfmark.def psdextra.def puarenc.def puenc.def puvnenc.def xr-hyper.sty \
  hluatex.def \
  hyperref-tds/tex/latex/hyperref

cd hyperref-tds
echo making tds zip
rm -r hyperref.tds.zip
zip -r hyperref.tds.zip  doc source tex
mv hyperref.tds.zip ../..



cd ../..
echo making main zip
rm -f hyperref.zip
zip -r hyperref.zip hyperref.tds.zip hyperref/{backref.dtx,backref.pdf,bmhydoc.sty,ChangeLog,ChangeLog.pdf,paperslides99.zip,doc/*.{gif,pdf,html,dict,css},hylatex.ltx,hyperref.dtx,hyperref.ins,hluatex.dtx,hyperref.pdf,manifest.txt,minitoc-hyper.sty,nameref.dtx,nameref.pdf,ntheorem-hyper.sty,psdmapshortnames.pl,README,README.pdf,xr-hyper.sty}
mv hyperref*.zip hyperref
